
package com.curse.addonservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AddOnService", targetNamespace = "http://addonservice.curse.com/", wsdlLocation = "http://addon-service.curse.com/AddOnService.svc?wsdl")
public class AddOnService
    extends Service
{

    private final static URL ADDONSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADDONSERVICE_EXCEPTION;
    private final static QName ADDONSERVICE_QNAME = new QName("http://addonservice.curse.com/", "AddOnService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://addon-service.curse.com/AddOnService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDONSERVICE_WSDL_LOCATION = url;
        ADDONSERVICE_EXCEPTION = e;
    }

    public AddOnService() {
        super(__getWsdlLocation(), ADDONSERVICE_QNAME);
    }

    public AddOnService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDONSERVICE_QNAME, features);
    }

    public AddOnService(URL wsdlLocation) {
        super(wsdlLocation, ADDONSERVICE_QNAME);
    }

    public AddOnService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDONSERVICE_QNAME, features);
    }

    public AddOnService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddOnService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IAddOnService
     */
    @WebEndpoint(name = "BinaryHttpAddOnServiceEndpoint")
    public IAddOnService getBinaryHttpAddOnServiceEndpoint() {
        return super.getPort(new QName("http://addonservice.curse.com/", "BinaryHttpAddOnServiceEndpoint"), IAddOnService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAddOnService
     */
    @WebEndpoint(name = "BinaryHttpAddOnServiceEndpoint")
    public IAddOnService getBinaryHttpAddOnServiceEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://addonservice.curse.com/", "BinaryHttpAddOnServiceEndpoint"), IAddOnService.class, features);
    }

    /**
     * 
     * @return
     *     returns IAddOnService
     */
    @WebEndpoint(name = "BinaryHttpsAddOnServiceEndpoint")
    public IAddOnService getBinaryHttpsAddOnServiceEndpoint() {
        return super.getPort(new QName("http://addonservice.curse.com/", "BinaryHttpsAddOnServiceEndpoint"), IAddOnService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAddOnService
     */
    @WebEndpoint(name = "BinaryHttpsAddOnServiceEndpoint")
    public IAddOnService getBinaryHttpsAddOnServiceEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://addonservice.curse.com/", "BinaryHttpsAddOnServiceEndpoint"), IAddOnService.class, features);
    }

    /**
     * 
     * @return
     *     returns IAddOnService
     */
    @WebEndpoint(name = "WsHttpAddOnServiceEndpoint")
    public IAddOnService getWsHttpAddOnServiceEndpoint() {
        return super.getPort(new QName("http://addonservice.curse.com/", "WsHttpAddOnServiceEndpoint"), IAddOnService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAddOnService
     */
    @WebEndpoint(name = "WsHttpAddOnServiceEndpoint")
    public IAddOnService getWsHttpAddOnServiceEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://addonservice.curse.com/", "WsHttpAddOnServiceEndpoint"), IAddOnService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDONSERVICE_EXCEPTION!= null) {
            throw ADDONSERVICE_EXCEPTION;
        }
        return ADDONSERVICE_WSDL_LOCATION;
    }

}
