
package com.curse.addonservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import addons.curse.AddOn;
import addons.curse.AddOnFile;
import addons.curse.ArrayOfAddOn;
import addons.curse.ArrayOfAddOnFile;
import addons.curse.ArrayOfFuzzyMatch;
import addons.curse.DownloadToken;
import addons.curse.FingerprintMatchResult;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOfintArrayOfAddOnFileHlmYZPzp;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOflong;
import org.datacontract.schemas._2004._07.curse.ArrayOfFolderFingerprint;
import org.datacontract.schemas._2004._07.curse.RepositoryMatch;
import org.datacontract.schemas._2004._07.curse_addonservice.ArrayOfAddOnFileKey;
import org.datacontract.schemas._2004._07.curse_clientservice.ArrayOfSyncTransaction;
import org.datacontract.schemas._2004._07.curse_clientservice.ArrayOfSyncedAddon;
import org.datacontract.schemas._2004._07.curse_clientservice.ESavedGameRestrictionLevel;
import org.datacontract.schemas._2004._07.curse_clientservice.ESavedGameStatus;
import org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponse;
import org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponseOfArrayOfSavedGameeheogrl4;
import org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponseOfArrayOfSyncedGameInstanceeheogrl4;
import org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponseOfESavedGameRestrictionLeveleheogrl4;
import org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponseOfSavedGameConstraintseheogrl4;
import org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponseOfSyncedGameInstanceeheogrl4;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IAddOnService", targetNamespace = "http://addonservice.curse.com/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    addons.curse.ObjectFactory.class,
    com.curse.addonservice.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.curse.ObjectFactory.class,
    org.datacontract.schemas._2004._07.curse_addonservice.ObjectFactory.class,
    org.datacontract.schemas._2004._07.curse_clientservice.ObjectFactory.class
})
public interface IAddOnService {


    /**
     * 
     * @param id
     * @return
     *     returns addons.curse.AddOn
     */
    @WebMethod(operationName = "GetAddOn", action = "http://addonservice.curse.com/IAddOnService/GetAddOn")
    @WebResult(name = "GetAddOnResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "GetAddOn", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetAddOn")
    @ResponseWrapper(localName = "GetAddOnResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetAddOnResponse")
    public AddOn getAddOn(
        @WebParam(name = "id", targetNamespace = "http://addonservice.curse.com/")
        Integer id);

    /**
     * 
     * @param gameSlug
     * @param addonSlug
     * @return
     *     returns org.datacontract.schemas._2004._07.curse.RepositoryMatch
     */
    @WebMethod(operationName = "GetRepositoryMatchFromSlug", action = "http://addonservice.curse.com/IAddOnService/GetRepositoryMatchFromSlug")
    @WebResult(name = "GetRepositoryMatchFromSlugResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "GetRepositoryMatchFromSlug", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetRepositoryMatchFromSlug")
    @ResponseWrapper(localName = "GetRepositoryMatchFromSlugResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetRepositoryMatchFromSlugResponse")
    public RepositoryMatch getRepositoryMatchFromSlug(
        @WebParam(name = "gameSlug", targetNamespace = "http://addonservice.curse.com/")
        String gameSlug,
        @WebParam(name = "addonSlug", targetNamespace = "http://addonservice.curse.com/")
        String addonSlug);

    /**
     * 
     * @param addonID
     * @param fileID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetChangeLog", action = "http://addonservice.curse.com/IAddOnService/GetChangeLog")
    @WebResult(name = "GetChangeLogResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "GetChangeLog", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetChangeLog")
    @ResponseWrapper(localName = "GetChangeLogResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetChangeLogResponse")
    public String getChangeLog(
        @WebParam(name = "addonID", targetNamespace = "http://addonservice.curse.com/")
        Integer addonID,
        @WebParam(name = "fileID", targetNamespace = "http://addonservice.curse.com/")
        Integer fileID);

    /**
     * 
     * @param addonID
     * @param fileID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://addonservice.curse.com/IAddOnService/v2GetChangeLog")
    @WebResult(name = "v2GetChangeLogResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "v2GetChangeLog", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.V2GetChangeLog")
    @ResponseWrapper(localName = "v2GetChangeLogResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.V2GetChangeLogResponse")
    public String v2GetChangeLog(
        @WebParam(name = "addonID", targetNamespace = "http://addonservice.curse.com/")
        Integer addonID,
        @WebParam(name = "fileID", targetNamespace = "http://addonservice.curse.com/")
        Integer fileID);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAddOnDescription", action = "http://addonservice.curse.com/IAddOnService/GetAddOnDescription")
    @WebResult(name = "GetAddOnDescriptionResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "GetAddOnDescription", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetAddOnDescription")
    @ResponseWrapper(localName = "GetAddOnDescriptionResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetAddOnDescriptionResponse")
    public String getAddOnDescription(
        @WebParam(name = "id", targetNamespace = "http://addonservice.curse.com/")
        Integer id);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://addonservice.curse.com/IAddOnService/v2GetAddOnDescription")
    @WebResult(name = "v2GetAddOnDescriptionResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "v2GetAddOnDescription", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.V2GetAddOnDescription")
    @ResponseWrapper(localName = "v2GetAddOnDescriptionResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.V2GetAddOnDescriptionResponse")
    public String v2GetAddOnDescription(
        @WebParam(name = "id", targetNamespace = "http://addonservice.curse.com/")
        Integer id);

    /**
     * 
     * @param addonID
     * @param fileID
     * @return
     *     returns addons.curse.AddOnFile
     */
    @WebMethod(operationName = "GetAddOnFile", action = "http://addonservice.curse.com/IAddOnService/GetAddOnFile")
    @WebResult(name = "GetAddOnFileResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "GetAddOnFile", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetAddOnFile")
    @ResponseWrapper(localName = "GetAddOnFileResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetAddOnFileResponse")
    public AddOnFile getAddOnFile(
        @WebParam(name = "addonID", targetNamespace = "http://addonservice.curse.com/")
        Integer addonID,
        @WebParam(name = "fileID", targetNamespace = "http://addonservice.curse.com/")
        Integer fileID);

    /**
     * 
     * @param ids
     * @return
     *     returns addons.curse.ArrayOfAddOn
     */
    @WebMethod(operationName = "GetAddOns", action = "http://addonservice.curse.com/IAddOnService/GetAddOns")
    @WebResult(name = "GetAddOnsResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "GetAddOns", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetAddOns")
    @ResponseWrapper(localName = "GetAddOnsResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetAddOnsResponse")
    public ArrayOfAddOn getAddOns(
        @WebParam(name = "ids", targetNamespace = "http://addonservice.curse.com/")
        ArrayOfint ids);

    /**
     * 
     * @param ids
     * @return
     *     returns addons.curse.ArrayOfAddOn
     */
    @WebMethod(action = "http://addonservice.curse.com/IAddOnService/v2GetAddOns")
    @WebResult(name = "v2GetAddOnsResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "v2GetAddOns", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.V2GetAddOns")
    @ResponseWrapper(localName = "v2GetAddOnsResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.V2GetAddOnsResponse")
    public ArrayOfAddOn v2GetAddOns(
        @WebParam(name = "ids", targetNamespace = "http://addonservice.curse.com/")
        ArrayOfint ids);

    /**
     * 
     * @param fingerprints
     * @return
     *     returns addons.curse.FingerprintMatchResult
     */
    @WebMethod(operationName = "GetFingerprintMatches", action = "http://addonservice.curse.com/IAddOnService/GetFingerprintMatches")
    @WebResult(name = "GetFingerprintMatchesResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "GetFingerprintMatches", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetFingerprintMatches")
    @ResponseWrapper(localName = "GetFingerprintMatchesResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetFingerprintMatchesResponse")
    public FingerprintMatchResult getFingerprintMatches(
        @WebParam(name = "fingerprints", targetNamespace = "http://addonservice.curse.com/")
        ArrayOflong fingerprints);

    /**
     * 
     * @param fingerprints
     * @return
     *     returns addons.curse.FingerprintMatchResult
     */
    @WebMethod(action = "http://addonservice.curse.com/IAddOnService/v2GetFingerprintMatches")
    @WebResult(name = "v2GetFingerprintMatchesResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "v2GetFingerprintMatches", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.V2GetFingerprintMatches")
    @ResponseWrapper(localName = "v2GetFingerprintMatchesResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.V2GetFingerprintMatchesResponse")
    public FingerprintMatchResult v2GetFingerprintMatches(
        @WebParam(name = "fingerprints", targetNamespace = "http://addonservice.curse.com/")
        ArrayOflong fingerprints);

    /**
     * 
     * @param gameID
     * @param folderFingerprints
     * @return
     *     returns addons.curse.ArrayOfFuzzyMatch
     */
    @WebMethod(operationName = "GetFuzzyMatches", action = "http://addonservice.curse.com/IAddOnService/GetFuzzyMatches")
    @WebResult(name = "GetFuzzyMatchesResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "GetFuzzyMatches", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetFuzzyMatches")
    @ResponseWrapper(localName = "GetFuzzyMatchesResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetFuzzyMatchesResponse")
    public ArrayOfFuzzyMatch getFuzzyMatches(
        @WebParam(name = "gameID", targetNamespace = "http://addonservice.curse.com/")
        Integer gameID,
        @WebParam(name = "folderFingerprints", targetNamespace = "http://addonservice.curse.com/")
        ArrayOfFolderFingerprint folderFingerprints);

    /**
     * 
     * @param fileID
     * @return
     *     returns addons.curse.DownloadToken
     */
    @WebMethod(operationName = "GetDownloadToken", action = "http://addonservice.curse.com/IAddOnService/GetDownloadToken")
    @WebResult(name = "GetDownloadTokenResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "GetDownloadToken", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetDownloadToken")
    @ResponseWrapper(localName = "GetDownloadTokenResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetDownloadTokenResponse")
    public DownloadToken getDownloadToken(
        @WebParam(name = "fileID", targetNamespace = "http://addonservice.curse.com/")
        Integer fileID);

    /**
     * 
     * @param hasPremium
     * @param subscriptionToken
     * @param userID
     * @param fileID
     * @return
     *     returns addons.curse.DownloadToken
     */
    @WebMethod(operationName = "GetSecureDownloadToken", action = "http://addonservice.curse.com/IAddOnService/GetSecureDownloadToken")
    @WebResult(name = "GetSecureDownloadTokenResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "GetSecureDownloadToken", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetSecureDownloadToken")
    @ResponseWrapper(localName = "GetSecureDownloadTokenResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetSecureDownloadTokenResponse")
    public DownloadToken getSecureDownloadToken(
        @WebParam(name = "fileID", targetNamespace = "http://addonservice.curse.com/")
        Integer fileID,
        @WebParam(name = "userID", targetNamespace = "http://addonservice.curse.com/")
        Integer userID,
        @WebParam(name = "hasPremium", targetNamespace = "http://addonservice.curse.com/")
        Boolean hasPremium,
        @WebParam(name = "subscriptionToken", targetNamespace = "http://addonservice.curse.com/")
        Integer subscriptionToken);

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponseOfArrayOfSyncedGameInstanceeheogrl4
     */
    @WebMethod(operationName = "GetSyncProfile", action = "http://addonservice.curse.com/IAddOnService/GetSyncProfile")
    @WebResult(name = "GetSyncProfileResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "GetSyncProfile", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetSyncProfile")
    @ResponseWrapper(localName = "GetSyncProfileResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetSyncProfileResponse")
    public ServiceResponseOfArrayOfSyncedGameInstanceeheogrl4 getSyncProfile();

    /**
     * 
     * @param gameID
     * @param instanceName
     * @param computerName
     * @param instanceLabel
     * @param instanceGUID
     * @return
     *     returns org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponseOfSyncedGameInstanceeheogrl4
     */
    @WebMethod(operationName = "CreateSyncGroup", action = "http://addonservice.curse.com/IAddOnService/CreateSyncGroup")
    @WebResult(name = "CreateSyncGroupResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "CreateSyncGroup", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.CreateSyncGroup")
    @ResponseWrapper(localName = "CreateSyncGroupResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.CreateSyncGroupResponse")
    public ServiceResponseOfSyncedGameInstanceeheogrl4 createSyncGroup(
        @WebParam(name = "instanceName", targetNamespace = "http://addonservice.curse.com/")
        String instanceName,
        @WebParam(name = "gameID", targetNamespace = "http://addonservice.curse.com/")
        Integer gameID,
        @WebParam(name = "computerName", targetNamespace = "http://addonservice.curse.com/")
        String computerName,
        @WebParam(name = "instanceGUID", targetNamespace = "http://addonservice.curse.com/")
        String instanceGUID,
        @WebParam(name = "instanceLabel", targetNamespace = "http://addonservice.curse.com/")
        String instanceLabel);

    /**
     * 
     * @param instanceID
     * @param computerName
     * @param instanceLabel
     * @param instanceGUID
     * @return
     *     returns org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponse
     */
    @WebMethod(operationName = "JoinSyncGroup", action = "http://addonservice.curse.com/IAddOnService/JoinSyncGroup")
    @WebResult(name = "JoinSyncGroupResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "JoinSyncGroup", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.JoinSyncGroup")
    @ResponseWrapper(localName = "JoinSyncGroupResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.JoinSyncGroupResponse")
    public ServiceResponse joinSyncGroup(
        @WebParam(name = "instanceID", targetNamespace = "http://addonservice.curse.com/")
        Integer instanceID,
        @WebParam(name = "computerName", targetNamespace = "http://addonservice.curse.com/")
        String computerName,
        @WebParam(name = "instanceGUID", targetNamespace = "http://addonservice.curse.com/")
        String instanceGUID,
        @WebParam(name = "instanceLabel", targetNamespace = "http://addonservice.curse.com/")
        String instanceLabel);

    /**
     * 
     * @param computerID
     * @param instanceID
     * @param instanceGUID
     * @return
     *     returns org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponse
     */
    @WebMethod(operationName = "LeaveSyncGroup", action = "http://addonservice.curse.com/IAddOnService/LeaveSyncGroup")
    @WebResult(name = "LeaveSyncGroupResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "LeaveSyncGroup", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.LeaveSyncGroup")
    @ResponseWrapper(localName = "LeaveSyncGroupResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.LeaveSyncGroupResponse")
    public ServiceResponse leaveSyncGroup(
        @WebParam(name = "instanceID", targetNamespace = "http://addonservice.curse.com/")
        Integer instanceID,
        @WebParam(name = "computerID", targetNamespace = "http://addonservice.curse.com/")
        Integer computerID,
        @WebParam(name = "instanceGUID", targetNamespace = "http://addonservice.curse.com/")
        String instanceGUID);

    /**
     * 
     * @param syncedAddons
     * @param instanceID
     * @return
     *     returns org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponse
     */
    @WebMethod(operationName = "SaveSyncSnapshot", action = "http://addonservice.curse.com/IAddOnService/SaveSyncSnapshot")
    @WebResult(name = "SaveSyncSnapshotResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "SaveSyncSnapshot", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.SaveSyncSnapshot")
    @ResponseWrapper(localName = "SaveSyncSnapshotResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.SaveSyncSnapshotResponse")
    public ServiceResponse saveSyncSnapshot(
        @WebParam(name = "instanceID", targetNamespace = "http://addonservice.curse.com/")
        Integer instanceID,
        @WebParam(name = "syncedAddons", targetNamespace = "http://addonservice.curse.com/")
        ArrayOfSyncedAddon syncedAddons);

    /**
     * 
     * @param instanceID
     * @param transactions
     * @return
     *     returns org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponse
     */
    @WebMethod(operationName = "SaveSyncTransactions", action = "http://addonservice.curse.com/IAddOnService/SaveSyncTransactions")
    @WebResult(name = "SaveSyncTransactionsResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "SaveSyncTransactions", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.SaveSyncTransactions")
    @ResponseWrapper(localName = "SaveSyncTransactionsResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.SaveSyncTransactionsResponse")
    public ServiceResponse saveSyncTransactions(
        @WebParam(name = "instanceID", targetNamespace = "http://addonservice.curse.com/")
        Integer instanceID,
        @WebParam(name = "transactions", targetNamespace = "http://addonservice.curse.com/")
        ArrayOfSyncTransaction transactions);

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponseOfArrayOfSavedGameeheogrl4
     */
    @WebMethod(operationName = "GetSavedGames", action = "http://addonservice.curse.com/IAddOnService/GetSavedGames")
    @WebResult(name = "GetSavedGamesResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "GetSavedGames", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetSavedGames")
    @ResponseWrapper(localName = "GetSavedGamesResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetSavedGamesResponse")
    public ServiceResponseOfArrayOfSavedGameeheogrl4 getSavedGames();

    /**
     * 
     * @param savedGameId
     * @return
     *     returns org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponse
     */
    @WebMethod(operationName = "DeleteSavedGame", action = "http://addonservice.curse.com/IAddOnService/DeleteSavedGame")
    @WebResult(name = "DeleteSavedGameResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "DeleteSavedGame", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.DeleteSavedGame")
    @ResponseWrapper(localName = "DeleteSavedGameResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.DeleteSavedGameResponse")
    public ServiceResponse deleteSavedGame(
        @WebParam(name = "savedGameId", targetNamespace = "http://addonservice.curse.com/")
        Integer savedGameId);

    /**
     * 
     * @param savedGameRevisionId
     * @param savedGameId
     * @return
     *     returns org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponse
     */
    @WebMethod(operationName = "DeleteSavedGameRevision", action = "http://addonservice.curse.com/IAddOnService/DeleteSavedGameRevision")
    @WebResult(name = "DeleteSavedGameRevisionResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "DeleteSavedGameRevision", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.DeleteSavedGameRevision")
    @ResponseWrapper(localName = "DeleteSavedGameRevisionResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.DeleteSavedGameRevisionResponse")
    public ServiceResponse deleteSavedGameRevision(
        @WebParam(name = "savedGameId", targetNamespace = "http://addonservice.curse.com/")
        Integer savedGameId,
        @WebParam(name = "savedGameRevisionId", targetNamespace = "http://addonservice.curse.com/")
        Integer savedGameRevisionId);

    /**
     * 
     * @param savedGameId
     * @param status
     * @return
     *     returns org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponse
     */
    @WebMethod(operationName = "SetSavedGameStatus", action = "http://addonservice.curse.com/IAddOnService/SetSavedGameStatus")
    @WebResult(name = "SetSavedGameStatusResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "SetSavedGameStatus", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.SetSavedGameStatus")
    @ResponseWrapper(localName = "SetSavedGameStatusResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.SetSavedGameStatusResponse")
    public ServiceResponse setSavedGameStatus(
        @WebParam(name = "savedGameId", targetNamespace = "http://addonservice.curse.com/")
        Integer savedGameId,
        @WebParam(name = "status", targetNamespace = "http://addonservice.curse.com/")
        ESavedGameStatus status);

    /**
     * 
     * @param savedGameId
     * @param name
     * @return
     *     returns org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponse
     */
    @WebMethod(operationName = "SetSavedGameName", action = "http://addonservice.curse.com/IAddOnService/SetSavedGameName")
    @WebResult(name = "SetSavedGameNameResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "SetSavedGameName", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.SetSavedGameName")
    @ResponseWrapper(localName = "SetSavedGameNameResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.SetSavedGameNameResponse")
    public ServiceResponse setSavedGameName(
        @WebParam(name = "savedGameId", targetNamespace = "http://addonservice.curse.com/")
        Integer savedGameId,
        @WebParam(name = "name", targetNamespace = "http://addonservice.curse.com/")
        String name);

    /**
     * 
     * @param savedGameId
     * @param description
     * @return
     *     returns org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponse
     */
    @WebMethod(operationName = "SetSavedGameDescription", action = "http://addonservice.curse.com/IAddOnService/SetSavedGameDescription")
    @WebResult(name = "SetSavedGameDescriptionResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "SetSavedGameDescription", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.SetSavedGameDescription")
    @ResponseWrapper(localName = "SetSavedGameDescriptionResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.SetSavedGameDescriptionResponse")
    public ServiceResponse setSavedGameDescription(
        @WebParam(name = "savedGameId", targetNamespace = "http://addonservice.curse.com/")
        Integer savedGameId,
        @WebParam(name = "description", targetNamespace = "http://addonservice.curse.com/")
        String description);

    /**
     * 
     * @param revisionId
     * @param savedGameId
     * @return
     *     returns org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponse
     */
    @WebMethod(operationName = "SetSavedGameDefaultRevision", action = "http://addonservice.curse.com/IAddOnService/SetSavedGameDefaultRevision")
    @WebResult(name = "SetSavedGameDefaultRevisionResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "SetSavedGameDefaultRevision", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.SetSavedGameDefaultRevision")
    @ResponseWrapper(localName = "SetSavedGameDefaultRevisionResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.SetSavedGameDefaultRevisionResponse")
    public ServiceResponse setSavedGameDefaultRevision(
        @WebParam(name = "savedGameId", targetNamespace = "http://addonservice.curse.com/")
        Integer savedGameId,
        @WebParam(name = "revisionId", targetNamespace = "http://addonservice.curse.com/")
        Integer revisionId);

    /**
     * 
     * @param revisionId
     * @param savedGameId
     * @return
     *     returns org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponse
     */
    @WebMethod(operationName = "SetSavedGameFavoriteRevision", action = "http://addonservice.curse.com/IAddOnService/SetSavedGameFavoriteRevision")
    @WebResult(name = "SetSavedGameFavoriteRevisionResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "SetSavedGameFavoriteRevision", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.SetSavedGameFavoriteRevision")
    @ResponseWrapper(localName = "SetSavedGameFavoriteRevisionResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.SetSavedGameFavoriteRevisionResponse")
    public ServiceResponse setSavedGameFavoriteRevision(
        @WebParam(name = "savedGameId", targetNamespace = "http://addonservice.curse.com/")
        Integer savedGameId,
        @WebParam(name = "revisionId", targetNamespace = "http://addonservice.curse.com/")
        Integer revisionId);

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponseOfSavedGameConstraintseheogrl4
     */
    @WebMethod(operationName = "GetSavedGameConstraints", action = "http://addonservice.curse.com/IAddOnService/GetSavedGameConstraints")
    @WebResult(name = "GetSavedGameConstraintsResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "GetSavedGameConstraints", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetSavedGameConstraints")
    @ResponseWrapper(localName = "GetSavedGameConstraintsResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetSavedGameConstraintsResponse")
    public ServiceResponseOfSavedGameConstraintseheogrl4 getSavedGameConstraints();

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponseOfESavedGameRestrictionLeveleheogrl4
     */
    @WebMethod(operationName = "GetSavedGameRestrictionLevel", action = "http://addonservice.curse.com/IAddOnService/GetSavedGameRestrictionLevel")
    @WebResult(name = "GetSavedGameRestrictionLevelResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "GetSavedGameRestrictionLevel", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetSavedGameRestrictionLevel")
    @ResponseWrapper(localName = "GetSavedGameRestrictionLevelResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetSavedGameRestrictionLevelResponse")
    public ServiceResponseOfESavedGameRestrictionLeveleheogrl4 getSavedGameRestrictionLevel();

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponse
     */
    @WebMethod(operationName = "UploadAvailableForUser", action = "http://addonservice.curse.com/IAddOnService/UploadAvailableForUser")
    @WebResult(name = "UploadAvailableForUserResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "UploadAvailableForUser", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.UploadAvailableForUser")
    @ResponseWrapper(localName = "UploadAvailableForUserResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.UploadAvailableForUserResponse")
    public ServiceResponse uploadAvailableForUser();

    /**
     * 
     * @param id
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetAddOnDump", action = "http://addonservice.curse.com/IAddOnService/GetAddOnDump")
    @WebResult(name = "GetAddOnDumpResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "GetAddOnDump", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetAddOnDump")
    @ResponseWrapper(localName = "GetAddOnDumpResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetAddOnDumpResponse")
    public byte[] getAddOnDump(
        @WebParam(name = "id", targetNamespace = "http://addonservice.curse.com/")
        Integer id);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ResetAllAddonCache", action = "http://addonservice.curse.com/IAddOnService/ResetAllAddonCache")
    @WebResult(name = "ResetAllAddonCacheResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "ResetAllAddonCache", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.ResetAllAddonCache")
    @ResponseWrapper(localName = "ResetAllAddonCacheResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.ResetAllAddonCacheResponse")
    public String resetAllAddonCache();

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ResetSingleAddonCache", action = "http://addonservice.curse.com/IAddOnService/ResetSingleAddonCache")
    @WebResult(name = "ResetSingleAddonCacheResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "ResetSingleAddonCache", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.ResetSingleAddonCache")
    @ResponseWrapper(localName = "ResetSingleAddonCacheResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.ResetSingleAddonCacheResponse")
    public String resetSingleAddonCache(
        @WebParam(name = "id", targetNamespace = "http://addonservice.curse.com/")
        Integer id);

    /**
     * 
     * @param restrictionLevel
     * @return
     *     returns org.datacontract.schemas._2004._07.curse_clientservice.ServiceResponse
     */
    @WebMethod(operationName = "SetSavedGameRestrictionLevel", action = "http://addonservice.curse.com/IAddOnService/SetSavedGameRestrictionLevel")
    @WebResult(name = "SetSavedGameRestrictionLevelResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "SetSavedGameRestrictionLevel", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.SetSavedGameRestrictionLevel")
    @ResponseWrapper(localName = "SetSavedGameRestrictionLevelResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.SetSavedGameRestrictionLevelResponse")
    public ServiceResponse setSavedGameRestrictionLevel(
        @WebParam(name = "restrictionLevel", targetNamespace = "http://addonservice.curse.com/")
        ESavedGameRestrictionLevel restrictionLevel);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HealthCheck", action = "http://addonservice.curse.com/IAddOnService/HealthCheck")
    @WebResult(name = "HealthCheckResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "HealthCheck", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.HealthCheck")
    @ResponseWrapper(localName = "HealthCheckResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.HealthCheckResponse")
    public String healthCheck();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CacheHealthCheck", action = "http://addonservice.curse.com/IAddOnService/CacheHealthCheck")
    @WebResult(name = "CacheHealthCheckResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "CacheHealthCheck", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.CacheHealthCheck")
    @ResponseWrapper(localName = "CacheHealthCheckResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.CacheHealthCheckResponse")
    public String cacheHealthCheck();

    /**
     * 
     * @param addOnID
     * @return
     *     returns addons.curse.ArrayOfAddOnFile
     */
    @WebMethod(operationName = "GetAllFilesForAddOn", action = "http://addonservice.curse.com/IAddOnService/GetAllFilesForAddOn")
    @WebResult(name = "GetAllFilesForAddOnResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "GetAllFilesForAddOn", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetAllFilesForAddOn")
    @ResponseWrapper(localName = "GetAllFilesForAddOnResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetAllFilesForAddOnResponse")
    public ArrayOfAddOnFile getAllFilesForAddOn(
        @WebParam(name = "addOnID", targetNamespace = "http://addonservice.curse.com/")
        Integer addOnID);

    /**
     * 
     * @param addOnFileKeys
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOfintArrayOfAddOnFileHlmYZPzp
     */
    @WebMethod(operationName = "GetAddOnFiles", action = "http://addonservice.curse.com/IAddOnService/GetAddOnFiles")
    @WebResult(name = "GetAddOnFilesResult", targetNamespace = "http://addonservice.curse.com/")
    @RequestWrapper(localName = "GetAddOnFiles", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetAddOnFiles")
    @ResponseWrapper(localName = "GetAddOnFilesResponse", targetNamespace = "http://addonservice.curse.com/", className = "com.curse.addonservice.GetAddOnFilesResponse")
    public ArrayOfKeyValueOfintArrayOfAddOnFileHlmYZPzp getAddOnFiles(
        @WebParam(name = "addOnFileKeys", targetNamespace = "http://addonservice.curse.com/")
        ArrayOfAddOnFileKey addOnFileKeys);

}
